---
title: "BCC Conference Round up"
description: "A hot day in the Big Carolina Conference at NE Creek Park"
date: "09/24/2025"
categories:
  - HighSchool
format: 
  html
execute:
    message: false
    warning: false
    echo: false
---

```{r}
library(tidyverse)
library(gt)
library(gtExtras)

meetID <- 'wodhcsciop'
source('../../ccMeetTools.R')
boysResults <- getFileName("Boys")
girlsResults <- getFileName("Girls")
boysVarsity <- read_excel(boysResults, sheet=getSheetName(meetID,"Boys","Varsity"))
girlsVarsity <- read_excel(girlsResults, sheet=getSheetName(meetID,"Girls","Varsity"))
```

## Competition summary
The course had a few more hills than typical ENC fare. Note: all spelling mistakes are from MileSplit.

### D.H. Conley Athlete times
```{r}
buildTeamTable(boysVarsity, "D.H. Conley",maxAth=16)
buildTeamTable(girlsVarsity, "D.H. Conley",maxAth=9)
```

### Boys
```{r}
scoreMeet(boysVarsity, "BCC Quad Meet", "Boys", "Varsity")
```

```{r}
#| fig-height: 5
makePlacePlot(boysVarsity, "BCC Quad Meet", "Boys", "Varsity")
```

```{r}
#| fig-height: 6.5
makeTimePlot(boysVarsity, "BCC Quad Meet", "Boys", "Varsity")
```

### Girls
```{r}
scoreMeet(girlsVarsity, "BCC Quad Meet", "Girls", "Varsity")
```

```{r}
#| fig-height: 5
makePlacePlot(girlsVarsity, "BCC Quad Meet", "Girls", "Varsity")
```

```{r}
#| fig-height: 6.5
makeTimePlot(girlsVarsity, "BCC Quad Meet", "Girls", "Varsity")
```
