---
title: "BCC Pitt County Schools Only"
description: "The unofficial county meet at Boyd Lee Park"
date: "09/17/2025"
categories:
  - HighSchool
  - BCC
format: 
  html
execute:
    message: false
    warning: false
    echo: false
---

```{r}
library(tidyverse)
library(gt)
library(gtExtras)

source('../../ccMeetTools.R')
meetID <- 'bcc-pitt-county'
boysResults <- '../../resources/bcc-pitt-only-09-17.xlsx'
boysVarsity <- read_excel(boysResults, sheet="Boys")
girlsResults <- '../../resources/bcc-pitt-only-09-17.xlsx'
girlsVarsity <- read_excel(girlsResults, sheet="Girls")
```

## Competition summary
This is the home course. 

### D.H. Conley Athlete times
```{r}
buildTeamTable(boysVarsity, "DH Conley",maxAth=13)
buildTeamTable(girlsVarsity, "DH Conley",maxAth=9)
```

### Boys
```{r}
scoreMeet(boysVarsity, meetID, "Boys", "Varsity")
```

```{r}
#| fig-height: 5
makePlacePlot(boysVarsity, meetID, "Boys", "Varsity")
```

```{r}
#| fig-height: 6.5
makeTimePlot(boysVarsity, meetID, "Boys", "Varsity")
```

### Girls
```{r}
scoreMeet(girlsVarsity, meetID, "Girls", "Varsity")
```

```{r}
#| fig-height: 5
makePlacePlot(girlsVarsity, meetID, "Girls", "Varsity")
```

```{r}
#| fig-height: 6.5
makeTimePlot(girlsVarsity, meetID, "Girls", "Varsity")
```
