---
title: "BCC Round Up - All teams"
description: "Home course"
date: "10/01/2025"
categories:
  - HighSchool
  - BCC
format: 
  html
execute:
    message: false
    warning: false
    echo: false
---

```{r}
library(tidyverse)
library(gt)
library(gtExtras)

source('../../ccMeetTools.R')
meetID <- 'bcc-round-up-boyd-lee-all-teams'
boysResults <- getFileName("Boys")
girlsResults <- getFileName("Girls")
boysVarsity <- read_excel(boysResults, sheet='bcc-round-up-boyd-lee-all-teams')
girlsVarsity <- read_excel(girlsResults, sheet=getSheetName(meetID,"Girls","Varsity"))
```

## Competition summary
All of the BCC teams were here today.

### D.H. Conley Athlete times
```{r}
buildTeamTable(boysVarsity, "D.H. Conley",maxAth=7)
buildTeamTable(girlsVarsity, "D.H. Conley",maxAth=7)
```

### Boys
```{r}
scoreMeet(boysVarsity, meetID, "Boys", "Varsity")
```

```{r}
#| fig-height: 5
makePlacePlot(boysVarsity, meetID, "Boys", "Varsity")
```

```{r}
#| fig-height: 6.5
makeTimePlot(boysVarsity, meetID, "Boys", "Varsity")
```

### Girls
```{r}
scoreMeet(girlsVarsity, meetID, "Girls", "Varsity")
```

```{r}
#| fig-height: 5
makePlacePlot(girlsVarsity, meetID, "Girls", "Varsity")
```

```{r}
#| fig-height: 6.5
makeTimePlot(girlsVarsity, meetID, "Girls", "Varsity")
```
