---
title: "JH Rose Kickoff"
description: ""
date: "08/26/2026"
categories:
  - HighSchool
format: 
  html
execute:
    message: false
    warning: false
    echo: false
---

```{r}
library(tidyverse)
library(gt)
library(gtExtras)
library(readxl)

source('../../ccMeetTools.R')
boysVarsity <- read_excel('roseKickoff26.xlsx', sheet='boys5000') |> 
  rename_with(~ str_to_title(.x)) 
girlsVarsity <- read_excel('roseKickoff26.xlsx', sheet='girls5000') |> 
  rename_with(~ str_to_title(.x)) 
```

## Competition summary
Boyd Lee was in good condition, although it was definitely late-August hot. New Bern, Rose, and South Central were other teams from our league.

### D.H. Conley Athlete times
Varsity athletes
```{r}
buildTeamTable(boysVarsity, "DHC", maxAth=14)
buildTeamTable(girlsVarsity, "Conley", maxAth=9)
```

### Boys
```{r}
scoreMeetSimp(boysVarsity, "Rose Kickoff Boys")
```

```{r}
#| fig-height: 5
mpp(boysVarsity, "Rose Kickoff Boys")
```

```{r}
#| fig-height: 6.5
mtp(boysVarsity, "Rose Kickoff Boys")
```

### Girls
```{r}
scoreMeetSimp(girlsVarsity, "Rose Kickoff Girls")
```

```{r}
#| fig-height: 5
mpp(girlsVarsity, "Rose Kickoff Girls")
```

```{r}
#| fig-height: 6.5
mtp(girlsVarsity, "Rose Kickoff Girls")
```
